force-app/main/default/objects/Mobile_Review__c/Mobile_Review__c.object-meta.xml
<CustomObject>
    <label>Mobile Review</label>
    <nameField>
        <label>MobileReview Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mobile Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mobile_Review__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Mobile_Review__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Mobile Reviews</relationshipLabel>
    <relationshipName>Mobile_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mobile_Review__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Mobile Reviews</relationshipLabel>
    <relationshipName>Mobile_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apple</fullName>
            </value>
            <value>
                <fullName>HTC</fullName>
            </value>
            <value>
                <fullName>Huawei</fullName>
            </value>
            <value>
                <fullName>Lenovo</fullName>
            </value>
            <value>
                <fullName>Motorola</fullName>
            </value>
            <value>
                <fullName>Nokia</fullName>
            </value>
            <value>
                <fullName>Samsung</fullName>
            </value>
            <value>
                <fullName>Sony</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Custom_OrderId__c.field-meta.xml
<CustomField>
    <fullName>Custom_OrderId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Custom OrderId</label>
    <referenceTo>Custom_Order__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Mobile_Review__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Review__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mobile Review</label>
    <referenceTo>Mobile_Review__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>2</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MobileDataService.cls
public with sharing class MobileDataService{
	@AuraEnabled(cacheable = true)
	public static List<Product2> getMobilesList(Integer offset, Integer pageSize, String mobileBrand){
		if (mobileBrand.equals('')){
			return [SELECT Name, Description, Picture__c, Price__c
			        FROM Product2 
			        LIMIT :pageSize
			        OFFSET :offset];
		} else{
			return [SELECT Name, Description, Picture__c, Price__c
			        FROM Product2 
			        WHERE Brand__c = :mobileBrand
			        LIMIT :pageSize
			        OFFSET :offset];
		}
	}

	@AuraEnabled
	public static List<Mobile_Review__c> getAllReviews(Id mobileId){
		return [SELECT Id, Name, Comment__c, Rating__c, LastModifiedDate, CreatedDate, Contact__c, Contact__r.Name
		        FROM Mobile_Review__c 
		        WHERE Product__c = :mobileId
		        ORDER BY CreatedDate DESC];
	}

	@AuraEnabled
	public static Integer totalRecords(String mobileBrand){
		if (mobileBrand.equals('')){
			System.debug(mobileBrand);
			return [SELECT COUNT()
			        FROM Product2 ];
		} else{
			System.debug(mobileBrand);
			return [SELECT COUNT()
			        FROM Product2 
			        WHERE Brand__c = :mobileBrand];
		}
	}

	@AuraEnabled(cacheable = true)
	public static Integer getNext(Integer offset, Integer pageSize){
		offset += pageSize;
		return offset;
	}

	@AuraEnabled(cacheable = true)
	public static Integer getPrevious(Integer offset, Integer pageSize){
		offset -= pageSize;
		return offset;
	}

	@AuraEnabled(cacheable = true)
	public static List<FatchValueWrapper> getMobileBrands(sObject objInfo, string picklistFieldApi){
		Schema.DescribeSObjectResult objDescribe = objInfo.getSObjectType().getDescribe();
		map<String, Schema.SObjectField> fieldMap = objDescribe.fields.getMap();
		list<Schema.PicklistEntry> values = fieldMap.get(picklistFieldApi).getDescribe().getPickListValues();
		list<FatchValueWrapper> objWrapper = new list<FatchValueWrapper>();
		for (Schema.PicklistEntry a : values){
			FatchValueWrapper oFatchValueWrapper = new FatchValueWrapper();
			oFatchValueWrapper.slabel = a.getLabel();
			oFatchValueWrapper.svalue = a.getValue();
			objWrapper.add(oFatchValueWrapper);
		}
		return objWrapper;
	}

	public with sharing class FatchValueWrapper{
		@auraEnabled
		public string slabel{ get; set; }

		@auraEnabled
		public string svalue{ get; set; }
	}

	@AuraEnabled(cacheable = true)
	public static List<Product2> getMobilesInOrder(String orderId){
		return [SELECT Id, Name, Picture__c, Price__c
		        FROM Product2 
		        WHERE Custom_OrderId__c = :orderId];
	}
}