force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Logo__c.field-meta.xml
<CustomField>
    <fullName>Logo__c</fullName>
    <label>Logo</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Account/fields/Working_hours__c.field-meta.xml
<CustomField>
    <fullName>Working_hours__c</fullName>
    <label>Working hours</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountController.cls
public with sharing class AccountController {
  @AuraEnabled(cacheable=true)
  public static Account getAccount(Id recordId) {
    Account accountToReturn = [
      SELECT
        Name,
        Description,
        Logo__c,
        Working_hours__c,
        Email__c,
        Phone,
        BillingStreet,
        BillingCity
      FROM Account
      WHERE ID = :recordId
    ];
    System.debug('accountToReturn' + accountToReturn);

    return accountToReturn;
  }
}