force-app/main/default/objects/Basket__c/Basket__c.object-meta.xml
<CustomObject>
    <label>Basket</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Basket Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Baskets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Basket__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ContactId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Baskets</relationshipLabel>
    <relationshipName>Baskets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Basket__c/fields/CustomOrderId__c.field-meta.xml
<CustomField>
    <fullName>CustomOrderId__c</fullName>
    <label>CustomOrderId</label>
    <referenceTo>Custom_Order__c</referenceTo>
    <relationshipLabel>Baskets</relationshipLabel>
    <relationshipName>Baskets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Basket__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ProductId</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Baskets</relationshipLabel>
    <relationshipName>Baskets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Basket__c/fields/ProductStatus__c.field-meta.xml
<CustomField>
    <fullName>ProductStatus__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked = add to Order
Unchecked = leave in the Basket</description>
    <label>ProductStatus</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Basket__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <description>equally Product2.Price</description>
    <label>UnitPrice</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Personal_discont__c.field-meta.xml
<CustomField>
    <fullName>Personal_discont__c</fullName>
    <label>Personal discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Custom_Order__c/Custom_Order__c.object-meta.xml
<CustomObject>
    <label>Custom Order</label>
    <nameField>
        <label>Custom Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Order__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Custom Orders</relationshipLabel>
    <relationshipName>Custom_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Order__c/fields/Delivery_date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_date__c</fullName>
    <label>Delivery date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Custom_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Awaiting payment</fullName>
            </value>
            <value>
                <fullName>Awaiting delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Order__c/fields/Type_of_payment__c.field-meta.xml
<CustomField>
    <fullName>Type_of_payment__c</fullName>
    <label>Type of payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>cash</fullName>
            </value>
            <value>
                <fullName>by card</fullName>
            </value>
            <value>
                <fullName>by card online</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apple</fullName>
            </value>
            <value>
                <fullName>HTC</fullName>
            </value>
            <value>
                <fullName>Huawei</fullName>
            </value>
            <value>
                <fullName>Lenovo</fullName>
            </value>
            <value>
                <fullName>Motorola</fullName>
            </value>
            <value>
                <fullName>Nokia</fullName>
            </value>
            <value>
                <fullName>Samsung</fullName>
            </value>
            <value>
                <fullName>Sony</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Flash_Memory__c.field-meta.xml
<CustomField>
    <fullName>Flash_Memory__c</fullName>
    <label>Flash Memory</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Operating_System__c.field-meta.xml
<CustomField>
    <fullName>Operating_System__c</fullName>
    <label>Operating System</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Android</fullName>
            </value>
            <value>
                <fullName>Apple iOS</fullName>
            </value>
            <value>
                <fullName>Windows Phone</fullName>
            </value>
            <value>
                <fullName>Symbian</fullName>
            </value>
            <value>
                <fullName>Nokia Series 30+</fullName>
            </value>
            <value>
                <fullName>KaiOS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/RAM__c.field-meta.xml
<CustomField>
    <fullName>RAM__c</fullName>
    <label>RAM</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Screen_Resolution__c.field-meta.xml
<CustomField>
    <fullName>Screen_Resolution__c</fullName>
    <label>Screen Resolution</label>
    <length>11</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Screen_Size__c.field-meta.xml
<CustomField>
    <fullName>Screen_Size__c</fullName>
    <label>Screen Size</label>
    <precision>2</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Total_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Total_Quantity__c</fullName>
    <label>Total Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestUpdateOrderTrigger.cls
@isTest
private class TestUpdateOrderTrigger {
  @TestSetup
  static void setData() {
    Product2 testProduct = new Product2(
      Name = 'Test',
      Price__c = 300,
      Total_Quantity__c = 3,
      Brand__c = 'Samsung',
      Flash_Memory__c = 64,
      Operating_System__c = 'Nokia Series 30+',
      RAM__c = 8,
      Screen_Resolution__c = '1024X1080',
      Screen_Size__c = 7
    );
    insert testProduct;

    Product2 selectedProduct = [
      SELECT Id, Price__c
      FROM Product2
      WHERE Name = 'Test'
    ];

    Contact testContact = new Contact(
      FirstName = 'John',
      LastName = 'Smithd',
      Personal_discont__c = 10
    );
    insert testContact;

    Contact selectedContact = [
      SELECT Id, Personal_discont__c
      FROM Contact
      WHERE FirstName = 'John' AND LastName = 'Smithd'
    ];

    Custom_Order__c testOrder = new Custom_Order__c(
      Name = 'testOrder',
      Status__c = 'Draft',
      ContactId__c = selectedContact.Id,
      Discount__c = selectedContact.Personal_discont__c
    );
    insert testOrder;

    Custom_Order__c selectedOrder = [
      SELECT Id, Status__c
      FROM Custom_Order__c
      WHERE Name = 'testOrder'
    ];

    Basket__c testBasket = new Basket__c(
      ProductId__c = selectedProduct.Id,
      ContactId__c = selectedContact.Id,
      CustomOrderId__c = selectedOrder.Id,
      ProductStatus__c = true,
      Quantity__c = 1,
      UnitPrice__c = selectedProduct.Price__c
    );
    insert testBasket;
  }

  @isTest
  static void testMethodTypeOfPaymentWithExeption() {
    System.debug('Userinfo.getProfileId() =' + Userinfo.getProfileId());

    // List<FieldPermissions> fpListForStatus = [
    //   SELECT
    //     SobjectType,
    //     Field,
    //     PermissionsRead,
    //     PermissionsEdit,
    //     Parent.ProfileId
    //   FROM FieldPermissions
    //   WHERE
    //     SobjectType = 'Custom_Order__c'
    //     AND Field = 'Custom_Order__c.Status__c'
    //     AND Parent.ProfileId = :Userinfo.getProfileId()
    // ];
    // System.debug(' fpListForStatus = ' + fpListForStatus);
    // if (!fpListForStatus.isEmpty()) {
    //   fpListForStatus[0].PermissionsEdit = false;
    // } else {
    //   System.debug('fpList.isEmpty');
    // }
    // update fpListForStatus;
    // System.debug(' fpListForStatus__c after update = ' + fpListForStatus);

    // List<FieldPermissions> fpListForTypeOfPayment = [
    //   SELECT
    //     SobjectType,
    //     Field,
    //     PermissionsRead,
    //     PermissionsEdit,
    //     Parent.ProfileId
    //   FROM FieldPermissions
    //   WHERE
    //     SobjectType = 'Custom_Order__c'
    //     AND Field = 'Custom_Order__c.Type_of_payment__c'
    //     AND Parent.ProfileId = :Userinfo.getProfileId()
    // ];

    // System.debug(' fpListForTypeOfPayment  = ' + fpListForTypeOfPayment);

    try {
      List<Custom_Order__c> customOrders = [
        SELECT Id, Name, Type_of_payment__c
        FROM Custom_Order__c
        WHERE Name = 'testOrder'
      ];
      System.debug('before update =' + customOrders);
      for (Custom_Order__c order : customOrders) {
        order.Type_of_payment__c = 'cash';
        System.debug('before trigger');
      }
      update customOrders;

      Custom_Order__c customOrderAfterUpdate = [
        SELECT Id, Status__c
        FROM Custom_Order__c
        WHERE Name = 'testOrder'
      ];

      System.debug('after update =' + customOrderAfterUpdate);
    } catch (Exception e) {
      System.debug(e.getMessage());
      System.debug('method testMethodTypeOfPaymentWithExeption catch');
      // System.assert(
      //   e.getMessage()
      //     .contains('first error: INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST'),
      //   e.getMessage()
      // );
    }
  }

  @isTest
  static void testMethodTypeOfPaymentEqualCashWithoutDelivery() {
    List<Custom_Order__c> customOrders = [
      SELECT Id, Type_of_payment__c
      FROM Custom_Order__c
      WHERE Name = 'testOrder'
    ];

    for (Custom_Order__c order : customOrders) {
      order.Type_of_payment__c = 'cash';
    }
    update customOrders;
    Custom_Order__c customOrderAfterUpdate = [
      SELECT Id, Status__c
      FROM Custom_Order__c
      WHERE Name = 'testOrder'
    ];
    System.assertEquals(
      customOrderAfterUpdate.Status__c,
      'Awaiting payment;Without delivery'
    );
  }

  @isTest
  static void testMethodTypeOfPaymentEqualCashWithDelivery() {
    List<Custom_Order__c> customOrders = [
      SELECT Id, Type_of_payment__c, Delivery_date__c
      FROM Custom_Order__c
      WHERE Name = 'testOrder'
    ];

    for (Custom_Order__c order : customOrders) {
      order.Type_of_payment__c = 'cash';
      order.Delivery_date__c = Date.today();
    }
    update customOrders;
    Custom_Order__c customOrderAfterUpdate = [
      SELECT Id, Status__c
      FROM Custom_Order__c
      WHERE Name = 'testOrder'
    ];
    System.assertEquals(
      customOrderAfterUpdate.Status__c,
      'Awaiting payment;Awaiting delivery'
    );
  }

  @isTest
  static void testMethodTypeOfPaymentEqualByCardWithoutDelivery() {
    List<Custom_Order__c> customOrders = [
      SELECT Id, Type_of_payment__c
      FROM Custom_Order__c
      WHERE Name = 'testOrder'
    ];

    for (Custom_Order__c order : customOrders) {
      order.Type_of_payment__c = 'by card';
    }
    update customOrders;
    Custom_Order__c customOrderAfterUpdate = [
      SELECT Id, Status__c
      FROM Custom_Order__c
      WHERE Name = 'testOrder'
    ];
    System.assertEquals(
      customOrderAfterUpdate.Status__c,
      'Awaiting payment;Without delivery'
    );
  }

  @isTest
  static void testMethodTypeOfPaymentEqualByCardWithDelivery() {
    List<Custom_Order__c> customOrders = [
      SELECT Id, Type_of_payment__c, Delivery_date__c
      FROM Custom_Order__c
      WHERE Name = 'testOrder'
    ];

    for (Custom_Order__c order : customOrders) {
      order.Type_of_payment__c = 'by card';
      order.Delivery_date__c = Date.today();
    }
    update customOrders;
    Custom_Order__c customOrderAfterUpdate = [
      SELECT Id, Status__c
      FROM Custom_Order__c
      WHERE Name = 'testOrder'
    ];
    System.assertEquals(
      customOrderAfterUpdate.Status__c,
      'Awaiting payment;Awaiting delivery'
    );
  }

  @isTest
  static void testMethodTypeOfPaymentEqualByCardOnlineWithoutDeliveryBeforePayPal() {
    List<Custom_Order__c> customOrders = [
      SELECT Id, Type_of_payment__c
      FROM Custom_Order__c
      WHERE Name = 'testOrder'
    ];

    for (Custom_Order__c order : customOrders) {
      order.Type_of_payment__c = 'by card online';
    }
    update customOrders;

    Custom_Order__c customOrderAfterUpdate = [
      SELECT Id, Status__c
      FROM Custom_Order__c
      WHERE Name = 'testOrder'
    ];
    System.assertEquals(customOrderAfterUpdate.Status__c, 'Without delivery');
  }

  @isTest
  static void testMethodTypeOfPaymentEqualByCardOnlineWithDeliveryBeforePayPal() {
    List<Custom_Order__c> customOrders = [
      SELECT Id, Type_of_payment__c, Delivery_date__c
      FROM Custom_Order__c
      WHERE Name = 'testOrder'
    ];

    for (Custom_Order__c order : customOrders) {
      order.Type_of_payment__c = 'by card online';
      order.Delivery_date__c = Date.today();
    }
    update customOrders;

    Custom_Order__c customOrderAfterUpdate = [
      SELECT Id, Status__c
      FROM Custom_Order__c
      WHERE Name = 'testOrder'
    ];
    System.assertEquals(customOrderAfterUpdate.Status__c, 'Awaiting delivery');
  }
}