force-app/main/default/objects/Basket__c/Basket__c.object-meta.xml
<CustomObject>
    <label>Basket</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Basket Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Baskets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Basket__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ContactId</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Baskets</relationshipLabel>
    <relationshipName>Baskets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Basket__c/fields/CustomOrderId__c.field-meta.xml
<CustomField>
    <fullName>CustomOrderId__c</fullName>
    <label>CustomOrderId</label>
    <referenceTo>Custom_Order__c</referenceTo>
    <relationshipLabel>Baskets</relationshipLabel>
    <relationshipName>Baskets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Basket__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ProductId</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Baskets</relationshipLabel>
    <relationshipName>Baskets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Basket__c/fields/ProductStatus__c.field-meta.xml
<CustomField>
    <fullName>ProductStatus__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked = add to Order
Unchecked = leave in the Basket</description>
    <label>ProductStatus</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Basket__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <description>equally Product2.Price</description>
    <label>UnitPrice</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Personal_discont__c.field-meta.xml
<CustomField>
    <fullName>Personal_discont__c</fullName>
    <label>Personal discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Custom_Order__c/Custom_Order__c.object-meta.xml
<CustomObject>
    <label>Custom Order</label>
    <nameField>
        <label>Custom Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Order__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Custom Orders</relationshipLabel>
    <relationshipName>Custom_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Order__c/fields/Delivery_date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_date__c</fullName>
    <label>Delivery date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Custom_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Awaiting payment</fullName>
            </value>
            <value>
                <fullName>Awaiting delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Order__c/fields/Total_Amount_With_Discount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_With_Discount__c</fullName>
    <formula>Total_Amount__c - Total_Amount__c  /100 *   Discount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount With Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Custom_Order__c/fields/Type_of_payment__c.field-meta.xml
<CustomField>
    <fullName>Type_of_payment__c</fullName>
    <label>Type of payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>cash</fullName>
            </value>
            <value>
                <fullName>by card</fullName>
            </value>
            <value>
                <fullName>by card online</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryAdress__c/DeliveryAdress__c.object-meta.xml
<CustomObject>
    <label>DeliveryAdress</label>
    <nameField>
        <label>DeliveryAdreess Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DeliveryAdreses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryAdress__c/fields/Adress__c.field-meta.xml
<CustomField>
    <fullName>Adress__c</fullName>
    <formula
  >Country__c  &amp; &quot;,&quot;&amp;  State__c   &amp; &quot;,&quot;&amp;  City__c  &amp; &quot;,&quot;&amp;  Street__c  &amp; &quot;,&quot;&amp;  PostalCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Adress</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryAdress__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryAdress__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>DeliveryAdreses</relationshipLabel>
    <relationshipName>DeliveryAdreses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryAdress__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apple</fullName>
            </value>
            <value>
                <fullName>HTC</fullName>
            </value>
            <value>
                <fullName>Huawei</fullName>
            </value>
            <value>
                <fullName>Lenovo</fullName>
            </value>
            <value>
                <fullName>Motorola</fullName>
            </value>
            <value>
                <fullName>Nokia</fullName>
            </value>
            <value>
                <fullName>Samsung</fullName>
            </value>
            <value>
                <fullName>Sony</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Flash_Memory__c.field-meta.xml
<CustomField>
    <fullName>Flash_Memory__c</fullName>
    <label>Flash Memory</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Operating_System__c.field-meta.xml
<CustomField>
    <fullName>Operating_System__c</fullName>
    <label>Operating System</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Android</fullName>
            </value>
            <value>
                <fullName>Apple iOS</fullName>
            </value>
            <value>
                <fullName>Windows Phone</fullName>
            </value>
            <value>
                <fullName>Symbian</fullName>
            </value>
            <value>
                <fullName>Nokia Series 30+</fullName>
            </value>
            <value>
                <fullName>KaiOS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/RAM__c.field-meta.xml
<CustomField>
    <fullName>RAM__c</fullName>
    <label>RAM</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Screen_Resolution__c.field-meta.xml
<CustomField>
    <fullName>Screen_Resolution__c</fullName>
    <label>Screen Resolution</label>
    <length>11</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Screen_Size__c.field-meta.xml
<CustomField>
    <fullName>Screen_Size__c</fullName>
    <label>Screen Size</label>
    <precision>2</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Total_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Total_Quantity__c</fullName>
    <label>Total Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/HttpResponseTest.cls
@isTest
private class HttpResponseTest {
  @TestSetup
  static void setData() {
    Product2 testProduct = new Product2(
      Name = 'Test',
      Price__c = 300,
      Total_Quantity__c = 3,
      Brand__c = 'Samsung',
      Flash_Memory__c = 64,
      Operating_System__c = 'Nokia Series 30+',
      RAM__c = 8,
      Screen_Resolution__c = '1024X1080',
      Screen_Size__c = 7
    );
    insert testProduct;

    Product2 selectedProduct = [
      SELECT Id, Price__c
      FROM Product2
      WHERE Name = 'Test'
    ];

    Contact testContact = new Contact(
      FirstName = 'John',
      LastName = 'Smithd',
      Personal_discont__c = 10
    );
    insert testContact;

    Contact selectedContact = [
      SELECT Id, Personal_discont__c
      FROM Contact
      WHERE FirstName = 'John' AND LastName = 'Smithd'
    ];

    DeliveryAdress__c adress = new DeliveryAdress__c(
      Name = 'Test adress',
      Country__c = '1',
      State__c = '1',
      City__c = '1',
      Street__c = '1',
      Contact__c = selectedContact.Id
    );
    insert adress;

    DeliveryAdress__c selectedAdress = [
      SELECT Id, Adress__c
      FROM DeliveryAdress__c
      WHERE Name = 'Test adress'
    ];

    List<Custom_Order__c> testOrders = new List<Custom_Order__c>();
    testOrders.add(
      new Custom_Order__c(
        Name = 'testOrder1',
        Status__c = 'Draft',
        ContactId__c = selectedContact.Id,
        Discount__c = selectedContact.Personal_discont__c
      )
    );
    testOrders.add(
      new Custom_Order__c(
        Name = 'testOrder2',
        Status__c = 'Draft',
        ContactId__c = selectedContact.Id,
        Discount__c = selectedContact.Personal_discont__c,
        Delivery_address__c = selectedAdress.Adress__c,
        Delivery_date__c = Date.today()
      )
    );
    insert testOrders;

    Custom_Order__c selectedOrder = [
      SELECT Id, Status__c
      FROM Custom_Order__c
      WHERE Name = 'testOrder1'
    ];

    Custom_Order__c selectedOrder2 = [
      SELECT Id, Status__c
      FROM Custom_Order__c
      WHERE Name = 'testOrder2'
    ];

    Basket__c testBasket = new Basket__c(
      ProductId__c = selectedProduct.Id,
      ContactId__c = selectedContact.Id,
      CustomOrderId__c = selectedOrder.Id,
      ProductStatus__c = true,
      Quantity__c = 1,
      UnitPrice__c = selectedProduct.Price__c
    );
    insert testBasket;

    Basket__c testBasket2 = new Basket__c(
      ProductId__c = selectedProduct.Id,
      ContactId__c = selectedContact.Id,
      CustomOrderId__c = selectedOrder2.Id,
      ProductStatus__c = true,
      Quantity__c = 1,
      UnitPrice__c = selectedProduct.Price__c
    );
    insert testBasket2;

    HelperForCustomOrderTrigger.firstcall = false;
    for (Custom_Order__c o : testOrders) {
      o.Type_of_payment__c = 'by card online';
    }
    update testOrders;
  }

  @isTest
  static void testCalloutWithoutDelivery() {
    List<Custom_Order__c> customOrders = [
      SELECT Id, Type_of_payment__c, Total_Amount_With_Discount__c, Status__c
      FROM Custom_Order__c
      WHERE Name = 'testOrder1'
    ];

    System.debug('customOrder = ' + customOrders);
    Test.startTest();
    // Set mock callout class
    Test.setMock(HttpCalloutMock.class, new MockHttpResponsePaypal());

    // Call method to test.
    // This causes a fake response to be sent
    // from the class that implements HttpCalloutMock.
    HttpResponse res = PayPalController.processPayments(customOrders[0]);

    // Verify response received contains fake values
    String contentType = res.getHeader('Content-Type');
    System.assert(contentType == 'application/json');
    String actualValue = res.getBody();
    String expectedValue = '{"example":"test"}';
    String actualValueStatus = res.getStatus();
    String expectedValueStatus = 'Created';
    System.assertEquals(actualValue, expectedValue);
    System.assertEquals(actualValueStatus, expectedValueStatus);
    System.assertEquals(201, res.getStatusCode());
    Test.stopTest();
  }

  @isTest
  static void testCalloutWithDelivery() {
    List<Custom_Order__c> customOrders = [
      SELECT Id, Type_of_payment__c, Total_Amount_With_Discount__c, Status__c
      FROM Custom_Order__c
      WHERE Name = 'testOrder2'
    ];

    System.debug('customOrder = ' + customOrders);
    Test.startTest();
    // Set mock callout class
    Test.setMock(HttpCalloutMock.class, new MockHttpResponsePaypal());

    // Call method to test.
    // This causes a fake response to be sent
    // from the class that implements HttpCalloutMock.
    HttpResponse res = PayPalController.processPayments(customOrders[0]);

    // Verify response received contains fake values
    String contentType = res.getHeader('Content-Type');
    System.assert(contentType == 'application/json');
    String actualValue = res.getBody();
    String expectedValue = '{"example":"test"}';
    String actualValueStatus = res.getStatus();
    String expectedValueStatus = 'Created';
    System.assertEquals(actualValue, expectedValue);
    System.assertEquals(actualValueStatus, expectedValueStatus);
    System.assertEquals(201, res.getStatusCode());
    Test.stopTest();
  }
}