force-app/main/default/objects/Contact/fields/Personal_discont__c.field-meta.xml
<CustomField>
    <fullName>Personal_discont__c</fullName>
    <label>Personal discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/DeliveryAdress__c/DeliveryAdress__c.object-meta.xml
<CustomObject>
    <label>DeliveryAdress</label>
    <nameField>
        <label>DeliveryAdreess Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DeliveryAdreses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryAdress__c/fields/Adress__c.field-meta.xml
<CustomField>
    <fullName>Adress__c</fullName>
    <formula
  >Country__c  &amp; &quot;,&quot;&amp;  State__c   &amp; &quot;,&quot;&amp;  City__c  &amp; &quot;,&quot;&amp;  Street__c  &amp; &quot;,&quot;&amp;  PostalCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Adress</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryAdress__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryAdress__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>DeliveryAdreses</relationshipLabel>
    <relationshipName>DeliveryAdreses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryAdress__c/fields/Custom_OrderId__c.field-meta.xml
<CustomField>
    <fullName>Custom_OrderId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Custom OrderId</label>
    <referenceTo>Custom_Order__c</referenceTo>
    <relationshipLabel>DeliveryAdreses</relationshipLabel>
    <relationshipName>DeliveryAdreses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DeliveryAdress__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>PostalCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryAdress__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContactController.cls
public with sharing class ContactController {
  @AuraEnabled(cacheable=true)
  public static List<Contact> getContacts(String contactId) {
    List<Contact> contacts = [
      SELECT FirstName, LastName, Email, Personal_discont__c
      FROM Contact
      WHERE Id = :contactId
    ];

    return contacts;
  }

  @AuraEnabled(cacheable=true)
  public static List<DeliveryAdress__c> getDeliveryAdress(String contactId) {
    List<DeliveryAdress__c> deliveryAdress = [
      SELECT
        Id,
        Country__c,
        State__c,
        City__c,
        Street__c,
        PostalCode__c,
        Adress__c
      FROM DeliveryAdress__c
      WHERE Contact__c = :contactId
    ];

    return deliveryAdress;
  }

  @AuraEnabled(cacheable=true)
  public static List<DeliveryAdress__c> getDeliveryAdressById(String id) {
    List<DeliveryAdress__c> deliveryAdress = [
      SELECT
        Id,
        Country__c,
        State__c,
        City__c,
        Street__c,
        PostalCode__c,
        Adress__c,
        Custom_OrderId__c
      FROM DeliveryAdress__c
      WHERE Id = :id
      LIMIT 1
    ];

    return deliveryAdress;
  }
}