force-app/main/default/objects/Chat_Message__c/Chat_Message__c.object-meta.xml
<CustomObject>
    <label>Chat Message</label>
    <nameField>
        <label>Chat Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chat Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chat_Message__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Chat Messages</relationshipLabel>
    <relationshipName>Chat_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Chat_Active__c.field-meta.xml
<CustomField>
    <fullName>Chat_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Chat_Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MediumPhotoUrl__c.field-meta.xml
<CustomField>
    <fullName>MediumPhotoUrl__c</fullName>
    <label>MediumPhotoUrl</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/ChatController.cls
public with sharing class ChatController {
  @AuraEnabled
  //   (cacheable=true)
  public static List<Chat_Message__c> getTodayMessages() {
    List<Chat_Message__c> messageList;
    try {
      messageList = [
        SELECT
          Id,
          Content__c,
          CreatedDate,
          Contact__r.MediumPhotoUrl__c,
          Contact__r.Name
        FROM Chat_Message__c
        WHERE CreatedDate = today
        ORDER BY CreatedDate DESC
      ];
    } catch (Exception e) {
      System.debug(e.getMessage());
      return null;
    }
    system.debug(messageList);
    return messageList;
  }

  @AuraEnabled(cacheable=true)
  public static List<Contact> getActiveChatUsers() {
    List<Contact> userList;
    try {
      userList = [
        SELECT Id, CreatedDate, Name, MediumPhotoUrl__c
        FROM Contact
        WHERE Chat_Active__c = TRUE
      ];
    } catch (Exception e) {
      System.debug(e.getMessage());
      return null;
    }
    return userList;
  }

  @AuraEnabled
  public static Contact setUserChatActive(String userId) {
    system.debug('userId' + userId);
    Contact userToUpdate;
    try {
      userToUpdate = [
        SELECT Id, Chat_Active__c
        FROM Contact
        WHERE Id = :userId
      ];
      userToUpdate.Chat_Active__c = true;
      update userToUpdate;
    } catch (DmlException e) {
      System.debug('An unexpected error has occurred: ' + e.getMessage());
    }
    return userToUpdate;
  }

  @AuraEnabled
  public static Contact setUserChatInactive(String userId) {
    system.debug('userId' + userId);
    Contact userToUpdate;
    try {
      userToUpdate = [
        SELECT Id, Chat_Active__c
        FROM Contact
        WHERE Id = :userId
      ];
      system.debug('userToUpdate1' + userToUpdate);
      userToUpdate.Chat_Active__c = false;
      system.debug('userToUpdate2' + userToUpdate);
      update userToUpdate;
    } catch (DmlException e) {
      System.debug('An unexpected error has occurred: ' + e.getMessage());
    }
    return userToUpdate;
  }
}